/**
 * DO NOT EDIT THIS FILE.
 * See the following change record for more information,
 * https://www.drupal.org/node/2815083
 * @preserve
 **/

(function ($, Drupal, drupalSettings) {
    Drupal.color = {
        logoChanged: false,
        callback: function callback(context, settings, $form) {
            if (!this.logoChanged) {
                $('.color-preview .color-preview-logo img').attr('src', drupalSettings.color.logo);
                this.logoChanged = true;
            }

            if (drupalSettings.color.logo === null) {
                $('div').remove('.color-preview-logo');
            }

            var $colorPreview = $form.find('.color-preview');
            var $colorPalette = $form.find('.js-color-palette');

            $colorPreview.find('.color-preview-tags li').hover(function (){
                $(this).css('background-color', $colorPalette.find('input[name="palette[discovermoretagsbghover]"]').val());
                $(this).css('color', $colorPalette.find('input[name="palette[discovermoretagshover]"]').val());
            },
            function (){
                $(this).css('background-color', $colorPalette.find('input[name="palette[discovermoretagsbg]"]').val());
                $(this).css('color', $colorPalette.find('input[name="palette[discovermoretagscolor]"]').val());
            });
            $colorPreview.find('.color-preview-main-menu-links a').hover(function (){
                $(this).css('border-color', $colorPalette.find('input[name="palette[menulinkhover]"]').val());
            },
            function (){
                $(this).css('border-color', $colorPalette.find('input[name="palette[menulinkhover]"]').val());
            });

            $colorPreview.find('.color-preview-header-top').css('background-color', $colorPalette.find('input[name="palette[top]"]').val());
            $colorPreview.find('.color-preview-header').css('background-color', $colorPalette.find('input[name="palette[bottom]"]').val());
            var headermenulinkhoverborder = $colorPalette.find('input[name="palette[menulinkhover]"]').val();
            $colorPreview.find('.color-preview-main-menu-links a:before').css('border-color', $colorPalette.find('input[name="palette[menulinkhover]"]').val());
            var cardexploretextcolor = $colorPalette.find('input[name="palette[explorebtntext]"]').val();
            $colorPreview.find('.color-preview-card-footer .explore a').css('color', $colorPalette.find('input[name="palette[explorebtntext]"]').val());
            var buttons = $colorPalette.find('input[name="palette[button]"]').val();
            $colorPreview.find('.preview-button1').css('background', $colorPalette.find('input[name="palette[button]"]').val());
            var subscribebuttons = $colorPalette.find('input[name="palette[subscribebutton]"]').val();
            $colorPreview.find('.preview-button2').css('color', $colorPalette.find('input[name="palette[subscribebutton]"]').val());
            var tagstext = $colorPalette.find('input[name="palette[discovermoretagscolor]"]').val();
            $colorPreview.find('.color-preview-tags li').css('color', $colorPalette.find('input[name="palette[discovermoretagscolor]"]').val());
            var tagsborder = $colorPalette.find('input[name="palette[discovermoretagsbg]"]').val();
            $colorPreview.find('.color-preview-tags li').css('border-color', $colorPalette.find('input[name="palette[discovermoretagscolor]"]').val());
            var tagsbg = $colorPalette.find('input[name="palette[discovermoretagsbghover]"]').val();
            $colorPreview.find('.color-preview-tags li:hover').css('background', $colorPalette.find('input[name="palette[discovermoretagsbghover]"]').val());
            var footerbg = $colorPalette.find('input[name="palette[footerbg]"]').val();
            $colorPreview.find('.color-preview-footer-wrapper').css('background', $colorPalette.find('input[name="palette[footerbg]"]').val());
          
        }
    };
})(jQuery, Drupal, drupalSettings);
