<?php

/**
 * @file
 * Module file for odpl_admin module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\node\Entity\Node;
use Drupal\user\Entity\User;
use Drupal\odpl_admin\OdplAdminInterface;

/**
 * Implements hook_form_alter().
 */
function odpl_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $user = Drupal::CurrentUser();
  $roles = $user->getRoles();
  if ($form_id == "user_form") {
    if (in_array('site_admin', $roles)) {
      $form['account']['current_pass'][OdplAdminInterface::FORM_ACCESS] = FALSE;
      $form['account']['name'][OdplAdminInterface::FORM_ACCESS] = TRUE;
      $form['account']['pass'][OdplAdminInterface::FORM_ACCESS] = FALSE;
      $form['actions']['back'] = [
        '#type' => 'button',
        '#value' => t('Back'),
        '#button_type' => 'primary',
        '#attributes' => [
          'onclick' => 'window.history.back();return false;',
        ],
      ];
    }
  }
  elseif ($form_id == 'node_api_product_edit_form' ||
  $form_id == 'node_blog_post_edit_form' || $form_id == 'node_landing_page_edit_form' ||
  $form_id == 'media_image_edit_form' || $form_id == 'node_use_case_edit_form' ||
  $form_id == 'node_forum_edit_form') {
    if (in_array('site_admin', $roles)) {
      $form['revision_information'][OdplAdminInterface::FORM_ACCESS] = FALSE;
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function odpl_admin_views_pre_render(ViewExecutable $view) {
  if ($view->storage->id() == 'media_library') {
    $view->element['#attached']['library'][] = 'odpl_admin/classy.media_library';
  }
}

/**
 * Implements hook_user_login() for site admin front page redirect.
 */
function odpl_admin_user_login($account) {
  $roles = $account->getRoles();
  if (in_array('site_admin', $roles) || in_array('editor', $roles)) {
    $url = '/content-management';
    $current_request = \Drupal::service('request_stack')->getCurrentRequest();
    $current_request->query->set(
      'destination', $url
    );
  }
}

/**
 * Implements hook_preprocess_HOOK() for menu dashboard link.
 */
function odpl_admin_preprocess_menu__account(&$variables) {
  foreach ($variables['items'] as $key => $item) {
    if ($item['title'] == 'My account' && count($item['below'])) {
      $user = Drupal::CurrentUser();
      $roles = $user->getRoles();
      foreach ($item['below'] as $k => $child) {
        if (in_array('site_admin', $roles) && $child['title'] == 'Dashboard') {
          unset($variables['items'][$key]['below'][$k]);
        }
        elseif (in_array('site_admin', $roles) && $child['title'] == 'Admin dashboard') {
          $variables['items'][$key]['below'][$k]['title'] = "Dashboard";
        }
        elseif ($child['title'] == 'Admin dashboard') {
          unset($variables['items'][$key]['below'][$k]);
        }
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK() for banner block.
 */
function odpl_admin_preprocess_block__banner_content_block(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  $referer = \Drupal::request()->headers->get('referer');
  $route_name = \Drupal::routeMatch()->getRouteName();
  $action = get_current_action_by_path($current_path);

  if ($route_name == 'entity.user.canonical') {
    $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Account Settings';
  }

  if ($route_name == 'entity.user.edit_form') {
    $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Edit Account Settings';
  }

  $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = get_banner_title_by_path($current_path);

  if ($action == 'Add') {
    if (str_contains($referer, OdplAdminInterface::API_LIST_PATH)) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'APIs - Add New';
    }
    if (str_contains($referer, 'content-management')) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Content Management - Add New';
    }
    if (str_contains($referer, 'forum-list')) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Forum - Add New';
    }
    if (str_contains($referer, 'admin/structure/taxonomy')) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Categories Management - Add New';
    }
    if (str_contains($referer, 'admin/structure/menu')) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Menu Management - Add New';
    }
  }

  if (in_array($action, ['Edit', 'Delete', 'Layout'])) {
    preg_match('!\d+!', $current_path, $matches);
    if (str_contains($current_path, '/node')) {
      $node = Node::load($matches[0]);
    }
    elseif (str_contains($current_path, '/user')) {
      $node = User::load($matches[0]);
    }
    if (str_contains($referer, OdplAdminInterface::API_LIST_PATH)) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'APIs - ' . $action . ' ' . $node->getTitle();
    }
    if (str_contains($referer, 'content-management')) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Content Management - ' . $action . ' ' . $node->getTitle();
    }
    if (str_contains($referer, 'forum-list')) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Forum - ' . $action . ' ' . $node->getTitle();
    }
    if (str_contains($referer, 'user-list')) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Manage Users - ' . $action . ' ' . $node->getAccountName();
    }
    if (str_contains($current_path, 'admin/structure/menu/item')) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Menu Management - Edit Menu Link';
    }
    if (str_contains($current_path, 'taxonomy/term')) {
      $variables['content'][OdplAdminInterface::BANNER_DATA]['title'][OdplAdminInterface::MARKUP_INDEX] = 'Categories Management - Edit Term';
    }
  }
}

/**
 *
 */
function get_banner_title_by_path($current_path) {
  $banner_title = '';

  if (str_contains($current_path, 'content-management')) {
    $banner_title = 'Content Management';
  }
  elseif (str_contains($current_path, '/admin/structure/menu')) {
    $banner_title = 'Menu Management';
  }
  elseif (str_contains($current_path, '/admin/structure/webform')) {
    $banner_title = 'Queries And Subscriptions';
  }
  elseif (str_contains($current_path, '/admin/structure/taxonomy')) {
    $banner_title = 'Categories Management';
  }
  elseif ($current_path == OdplAdminInterface::API_LIST_PATH) {
    $banner_title = 'APIs';
  }
  elseif ($current_path == '/user-list') {
    $banner_title = 'Manage Users';
  }
  elseif ($current_path == '/forum-list') {
    $banner_title = 'Forum';
  }
  elseif ($current_path == '/webform-submission') {
    $banner_title = 'Queries And Subscriptions';
  }
  elseif ($current_path == '/admin/reports/google-analytics-reports/summary') {
    $banner_title = 'Google Analytics';
  }
  elseif ($current_path == '/google-analytics-reports') {
    $banner_title = 'Google Analytics';
  }

  return $banner_title;
}

/**
 *
 */
function get_current_action_by_path($current_path) {
  if (str_contains($current_path, '/add')) {
    $action = 'Add';
  }
  elseif (str_contains($current_path, '/edit')) {
    $action = 'Edit';
  }
  elseif (str_contains($current_path, '/delete')) {
    $action = 'Delete';
  }
  elseif (str_contains($current_path, '/layout')) {
    $action = 'Layout';
  }

  return $action;
}
