<?php

/**
 * @file
 * Contains odpl_notification.module.
 */

/**
 * Implements hook_theme().
 *
 * Twig template for render notification content.
 */
function odpl_notification_theme($existing, $type, $theme, $path) {
  return [
    'odpl_notification' => [
      'variables' => [
        'uid' => NULL,
        'notification_type' => NULL,
        'total' => NULL,
        'unread' => NULL,
        'notification_list' => NULL,
      ],
    ],
  ];
}
