name: CI
on: [pull_request]

jobs:
  check-drupal-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Install PHPCS
        run: composer global require --dev drupal/coder dealerdirect/phpcodesniffer-composer-installer

      - name: Clone the code
        uses: actions/checkout@v2
      
      - name: Check coding standards
        run: ~/.composer/vendor/bin/phpcs --standard="Drupal,DrupalPractice" --extensions="module,inc,install,test,profile,theme,info,txt,md,yml" .

  check-php-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v2

      - name: Set up PHP 7.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      - name: Composer install
        run: composer install

      - name: Analyse codebase
        run: ./vendor/bin/phpstan analyse .
