name: CI
on: [pull_request]

jobs:
  check-drupal-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Install PHPCS
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require --dev drupal/coder dealerdirect/phpcodesniffer-composer-installer

      - name: Clone the code
        uses: actions/checkout@v2

      - name: Check coding standards
        run: ~/.composer/vendor/bin/phpcs --ignore=themes/custom/ezdevportal_theme/css/* --standard="Drupal,DrupalPractice" --extensions="module,inc,install,test,profile,theme,css,info,txt,md,yml" .
